FROM golang:alpine AS build

RUN set -ex && \
	apk add --no-progress --no-cache \
	gcc \
	musl-dev

WORKDIR /app
COPY . .

RUN go mod download

RUN go build -tags musl -o /app/go-server

FROM alpine

COPY --from=build /app/go-server /app/go-server

ARG HTTP_SERVER_PORT
ENV HTTP_SERVER_PORT=$HTTP_SERVER_PORT

ARG INFLUXDB_HOST
ENV INFLUXDB_HOST=$INFLUXDB_HOST

ARG INFLUXDB_PORT
ENV INFLUXDB_PORT=$INFLUXDB_PORT

ARG INFLUXDB_TOKEN
ENV INFLUXDB_TOKEN=$INFLUXDB_TOKEN

ARG INFLUXDB_ORG
ENV INFLUXDB_ORG=$INFLUXDB_ORG

ARG INFLUXDB_BUCKET
ENV INFLUXDB_BUCKET=$INFLUXDB_BUCKET

ARG INFLUXDB_MEASUREMENT
ENV INFLUXDB_MEASUREMENT=$INFLUXDB_MEASUREMENT

ENTRYPOINT [ "/app/go-server" ]